default:
  image: mcr.microsoft.com/powershell

variables:
  AZURE_SUBSCRIPTION_ID:
    description: "Subscription ID of the Azure subscription to use for the deployment"
    value: ""

  RESOURCE_GROUP_NAME:
    description: "Resource group name of the Azure resource group to use for the deployment"
    value: ""

  VM_NAME:
    description: "VM name of the Azure VM to use for the deployment"
    value: ""

  ISOLATION_SUBNET_RANGE:
    description: "Isolation subnet range to use for the deployment"
    value: ""

  BASTION_SUBNET_RANGE:
    description: "Bastion subnet range to use for the deployment"
    value: ""

stages:
  - isolate_vm

isolate_vm:
  stage: isolate_vm
  script:
  - pwsh -Command "& { . .\IsolateVM.ps1; Invoke-IsolateVM -AzureTenantId $AZURE_TENANT_ID -AzureClientId $AZURE_CLIENT_ID -AzureClientSecret $AZURE_CLIENT_SECRET -subscriptionId $AZURE_SUBSCRIPTION_ID -VMresourceGroupName $RESOURCE_GROUP_NAME -vmName $VM_NAME -subnetRange $ISOLATION_SUBNET_RANGE -bastionSubnet $BASTION_SUBNET_RANGE }"